# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://github.com/nodejs/release#release-schedule
        # https://github.com/actions/setup-node#supported-version-syntax
        node-version:
        - "lts/*"
        - "latest"

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node-version }}

    - name: Log the Node.js version used
      run: echo "::notice::Using Node.js $(node -v)"

    - name: Install dependencies
      run: npm ci

    - name: Run the tests
      run: npm test

    # https://github.com/marketplace/actions/coveralls-github-action
    # upload coverage report for just one of Node.js version matrix runs
    - name: Upload coverage report to Coveralls
      if: matrix.node-version == 'lts/*'
      uses: coverallsapp/github-action@v2.3.6
      continue-on-error: true
      with:
        github-token: ${{ github.token }}
